/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as error403RouteImport } from './routes/(error)/403'
import { Route as error404RouteImport } from './routes/(error)/404'
import { Route as error500RouteImport } from './routes/(error)/500'
import { Route as AuthenticatedPostIndexRouteImport } from './routes/_authenticated/post/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const error403Route = error403RouteImport.update({
  id: '/(error)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const error404Route = error404RouteImport.update({
  id: '/(error)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const error500Route = error500RouteImport.update({
  id: '/(error)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostIndexRoute = AuthenticatedPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/403': typeof error403Route
  '/404': typeof error404Route
  '/500': typeof error500Route
  '/post/': typeof AuthenticatedPostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/403': typeof error403Route
  '/404': typeof error404Route
  '/500': typeof error500Route
  '/post': typeof AuthenticatedPostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(error)/403': typeof error403Route
  '/(error)/404': typeof error404Route
  '/(error)/500': typeof error500Route
  '/_authenticated/post/': typeof AuthenticatedPostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/403' | '/404' | '/500' | '/post/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/403' | '/404' | '/500' | '/post'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(error)/403'
    | '/(error)/404'
    | '/(error)/500'
    | '/_authenticated/post/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  error403Route: typeof error403Route
  error404Route: typeof error404Route
  error500Route: typeof error500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/403': {
      id: '/(error)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof error403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/404': {
      id: '/(error)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof error404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(error)/500': {
      id: '/(error)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof error500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post/': {
      id: '/_authenticated/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof AuthenticatedPostIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPostIndexRoute: typeof AuthenticatedPostIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPostIndexRoute: AuthenticatedPostIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  error403Route: error403Route,
  error404Route: error404Route,
  error500Route: error500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
